# version: '3'
# services:
#   backend:
#     build:
#       context: ./app
#       dockerfile: Dockerfile
#     ports:
#       - 5000:5000
#     volumes:
#       - ./app:/app
#     depends_on:
#       - model

#   model:
#     build:
#       context: ./model
#       dockerfile: Dockerfile.model
#     volumes:
#       - ./model:/model
version: '3'
services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - mynetwork
    depends_on:
      - model

  model:
    build:
      context: ./model
      dockerfile: Dockerfile.model
    volumes:
      - ./model:/model
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
